name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hello, thanks for posting and Issue, your response is very valuable to us. Our team will look into it and fix it as soon as possible. Please remember that this is a work in progress and your feedback will improve the build greatly!"
        pr-message: "Hello, thank you for posting a pull requeesting. Your feedback and work is vey important as we grow, out team will be sure to look into this and contact you soon."
